user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

estados:
    resource: "@UtilBundle/Controller/EstadosController.php"
    type:     rest
    prefix:   /estados

cidades:
    resource: "@UtilBundle/Controller/CidadesController.php"
    type:     rest
    prefix:   /cidades

bairros:
    resource: "@UtilBundle/Controller/BairrosController.php"
    type:     rest
    prefix:   /bairros

alunos:
    type:     rest
    resource: Serbinario\Bundles\SerAcademicoBundle\Controller\AlunosController

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

#serbinario_oauth_server_auth_login_check:
#    pattern:  /oauth/v2/auth_login_check
#    defaults: { _controller: UserBundle:Default:loginCheck }
