security:
    encoders:
        Serbinario\Bundles\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        serbinario_provider:
             id: app.serbinario.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/*
            fos_oauth:  true
            stateless:  true


    access_control:
        # You can omit this if /api can be accessed both authenticated and anonymously
        - { path: ^/alunos/*, roles: [ ROLE_ADMIN ] }

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
